---
- name: create a resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: westus

- name: create the virtual network
  azure_rm_virtualnetwork:
    name: giropops-virtual-net
    resource_group: "{{ resource_group }}"
    address_prefixes_cidr: "10.0.0.0/16"
  register: vn

- name: create a security group
  azure_rm_securitygroup:
    name: giropops-security
    resource_group: "{{ resource_group }}"
    purge_rules: yes
    rules:
      - name: allow SSH
        protocol: Tcp
        destination_port_range: 22
        priority: 101
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: kube-api server
        protocol: Tcp
        destination_port_range: 6443
        priority: 102
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: etcd api
        protocol: Tcp
        destination_port_range: 2379
        priority: 103
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: kubelet api
        protocol: Tcp
        destination_port_range: 10250
        priority: 104
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: kube-scheduler
        protocol: Tcp
        destination_port_range: 10251
        priority: 105
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: kube controller manager
        protocol: Tcp
        destination_port_range: 10252
        priority: 106
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: kubelet api read only
        protocol: Tcp
        destination_port_range: 10255
        priority: 107
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: nodeport service
        protocol: Tcp
        destination_port_range: 30000
        priority: 108
        access: Allow
        source_address_prefix:
          - "0.0.0.0/0"
        direction: Inbound
      - name: allow all
        protocol: "*"
        priority: 109
        access: Allow
        direction: Outbound
  register: sg

- name: create the virtual subnet
  azure_rm_subnet:
    name: giropops-subnet
    resource_group: "{{ resource_group }}"
    virtual_network_name: "{{ vn.state.name }}"
    address_prefix_cidr: "10.0.1.0/24"
    security_group:
      name: "{{ sg.state.name  }}"
      resource_group: "{{ resource_group }}"
  register: sn

- name: create the public IP
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}_{{ item }}"
    allocation_method: Static
  loop:
    - 1
    - 2
    - 3

- name: create virtual network interface
  azure_rm_networkinterface:
    name: "{{ vm_name }}_{{ item }}"
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ vn.state.name }}"
    subnet: "{{ sn.state.name }}"
    public_ip_name: "{{ vm_name }}_{{ item }}"
    security_group: "{{ sg.state.name }}"
  loop:
    - 1
    - 2
    - 3

- name: create vm
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}-{{ item }}"
    vm_size: "{{ size }}"
    admin_username: "{{ user }}"
    admin_password: "{{ pass }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ user }}/.ssh/authorized_keys"
        key_data: "{{ key }}"
    network_interfaces: "{{ vm_name }}_{{ item }}"
    image:
      offer: "{{ offer }}"
      publisher: "{{ publisher }}"
      sku: "{{ sku }}"
      version: "{{ version }}"
  loop:
    - 1
    - 2
    - 3

- name: get facts about private IP address
  azure_rm_networkinterface_info:
    resource_group: "{{ resource_group }}"
  register: priv_ip_info

- name: get facts about public IP address
  azure_rm_publicipaddress_info:
    resource_group: "{{ resource_group }}"
  register: pub_ip_info

- name: add public ip master node
  local_action:
    module: lineinfile
    path: ./hosts
    insertafter: '\[master]'
    firstmatch: yes
    line: "{{ pub_ip_info.publicipaddresses[item].ip_address }}"
  loop:
    - 0

- name: add public ip worker node
  local_action:
    module: lineinfile
    path: ./hosts
    insertafter: '\[workers]'
    firstmatch: yes
    line: "{{ pub_ip_info.publicipaddresses[item].ip_address }}"
  loop:
    - 1
    - 2


- name: add node k8s master private ip
  local_action:
    module: lineinfile
    path: ./hosts
    insertafter: '\[workers:vars]'
    line: "K8S_MASTER_NODE_IP={{ priv_ip_info.networkinterfaces[item].ip_configurations[0].private_ip_address }}"
  loop:
    - 0

- name: aguardando o ssh
  local_action:
    module: wait_for
    host: "{{ pub_ip_info.publicipaddresses[item].ip_address }}"
    port: 22
    state: started
  loop:
    - 0
    - 1
    - 2
