---
- hosts: all
  become: yes
  pre_tasks:
    - name: 'Atualizando repos'
      raw: 'apt update'
    - name: 'Instalando python'
      raw: 'apt install -y python'
    - name: 'Instalando pacotes necessarios'
      raw: 'apt install -y apt-transport-https ca-certificates curl'
  roles:
    - { role: install_k8s, tags: ["install kubernetes"]}

- hosts: master
  become: yes
  roles:
    - { role: create_cluster, tags: ["create kubernetes cluster"]

- hosts: workers
  become: yes
  roles:
    - { role: join_workers, tags: ["join workers into the cluster"]
