---
- name: install docker engine
  shell: curl -fsSL https://get.docker.com | bash -

- name: configure docker
  shell:
    cat > /etc/docker/daemon.json <<EOF
    {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "storage-driver": "overlay2",
      "storage-opts": [
        "overlay2.override_kernel_check=true"
      ]
    }
    EOF

- name: systemd directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
