---
- name: add k8s repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present 

- name: add k8s repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: install k8s packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - kubelet
    - kubectl
    - kubeadm

- name: desativar o swap
  command: swapoff -a

- name: garante o trafego na bridge
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_values:
  - net.brigde.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
